"""HARVEST_DECISIONS.md builder.

Applies the 5-rule algorithm (02-HARVEST_SCOPE.md § B/C 위임) to B/C 26
entries and emits a 39-row 5-column markdown table. A-class 13 rows are
copied verbatim from 02-HARVEST_SCOPE.md §A.

5 rules (priority order):
  1. Blacklist match → 폐기
  2. Scope boundary (longform/incidents_jp/worktree/duo_japan) → 폐기
  3. Session 77+ canonical forms → 승계 신형
  4. C-class + cosmetic cleanup (gitignore/worktree_copy/.tmp_/_backup_) → cleanup
  5. Default → 통합-재작성
"""
from __future__ import annotations

import re
from pathlib import Path

_SCOPE_BOUNDARY_TOKENS = (
    "longform/",
    "incidents_jp",
    "duo_japan",
    "worktree",
)

_CLEANUP_TOKENS = (
    "gitignore",
    "worktree_copy",
    ".tmp_",
    "_backup_",
)

_SESSION_CANONICAL_RE = re.compile(r"세션\s*(7[7-9]|8\d|9\d)")
_SEVENTEENTH_UNCOMMITTED_RE = re.compile(r"17일\s*uncommitted")


def judge(entry: dict, body: str, blacklist: list[dict]) -> tuple[str, str]:
    """Apply 5-rule algorithm. Returns (verdict, rationale).

    Rationale cites the rule number so audits can trace which rule
    produced the verdict.
    """
    # Rule 1: blacklist precedence
    for bl in blacklist:
        selector = bl.get("file") or bl.get("path") or bl.get("pattern")
        if selector and selector in body:
            return ("폐기", f"rule 1: blacklist match ({selector})")

    # Rule 2: scope boundary (shorts-only studio)
    for token in _SCOPE_BOUNDARY_TOKENS:
        if token in body:
            return ("폐기", f"rule 2: scope boundary ({token})")

    # Rule 3: Session 77+ canonical forms
    if _SESSION_CANONICAL_RE.search(body) or _SEVENTEENTH_UNCOMMITTED_RE.search(body):
        return ("승계 신형", "rule 3: session 77+ canonical / 17일 uncommitted")

    # Rule 4: C-class cosmetic cleanup
    if entry["class"] == "C":
        for token in _CLEANUP_TOKENS:
            if token in body:
                return ("cleanup", f"rule 4: cosmetic cleanup ({token})")

    # Rule 5: default
    return ("통합-재작성", "rule 5: default — integrate with rewrite")


_A_TABLE_RE = re.compile(
    r"^\| A-\d+ \| .*\|$",
    re.MULTILINE,
)


def _extract_a_rows(scope_md_path: Path) -> list[str]:
    """Extract A-1..A-13 verbatim table rows from 02-HARVEST_SCOPE.md §A."""
    text = scope_md_path.read_text(encoding="utf-8")
    rows = _A_TABLE_RE.findall(text)
    if len(rows) != 13:
        raise ValueError(
            f"Expected 13 A-class rows in 02-HARVEST_SCOPE.md, got {len(rows)}"
        )
    return rows


def build_decisions_md(
    conflict_entries: list[dict],
    blacklist: list[dict],
    scope_md_path: Path,
    conflict_map_path: Path,
    out_path: Path,
) -> None:
    """Emit 39-row HARVEST_DECISIONS.md.

    Layout:
      - Header + note
      - 5-column table: | ID | 드리프트 요약 | 판정 | 근거 | 실행 지시 |
      - A-1..A-13 copied verbatim from 02-HARVEST_SCOPE.md §A
      - B-1..B-16 + C-1..C-10 generated by judge() per entry body

    Raises:
        ValueError: A-class row count mismatch or conflict_entries count != 39.
    """
    if len(conflict_entries) != 39:
        raise ValueError(
            f"conflict_entries count mismatch: expected 39, got {len(conflict_entries)}"
        )

    a_rows = _extract_a_rows(scope_md_path)

    # Import inline to avoid circular import at module load
    from scripts.harvest.conflict_parser import extract_entry_body

    bc_rows: list[str] = []
    for entry in conflict_entries:
        if entry["class"] == "A":
            continue  # A rows come from verbatim copy
        body = extract_entry_body(conflict_map_path, entry["id"])
        verdict, rationale = judge(entry, body, blacklist)
        instruction = f"Phase 4+ 에이전트 설계 시 rule {rationale.split(':')[0].split()[-1]} 적용"
        summary = entry["summary"].replace("|", "\\|")
        rationale_esc = rationale.replace("|", "\\|")
        bc_rows.append(
            f"| {entry['id']} | {summary} | **{verdict}** | {rationale_esc} | {instruction} |"
        )

    header_lines = [
        "# HARVEST_DECISIONS — Phase 3 전수 판정 결과",
        "",
        "**Source:** `.planning/phases/02-domain-definition/02-HARVEST_SCOPE.md` (A급 13 사전 판정)",
        "**Generator:** `scripts/harvest/decision_builder.py` (5-rule algorithm, B/C 26 판정)",
        "**CONFLICT_MAP:** 39 entries (A:13 verbatim + B:16 + C:10 algorithm)",
        "",
        "## 5-rule 알고리즘 (B/C 26 적용)",
        "",
        "1. Harvest blacklist match → 폐기",
        "2. Scope boundary (longform/incidents_jp/worktree/duo_japan) → 폐기",
        "3. Session 77+ canonical forms → 승계 신형",
        "4. C-class + cosmetic cleanup (gitignore/worktree_copy/.tmp_/_backup_) → cleanup",
        "5. Default → 통합-재작성",
        "",
        "## 39 전수 판정 테이블",
        "",
        "| ID | 드리프트 요약 | 판정 | 근거 | 실행 지시 |",
        "|----|---------------|------|------|-----------|",
    ]

    lines: list[str] = header_lines[:]
    lines.extend(a_rows)
    lines.extend(bc_rows)
    lines.append("")
    lines.append(
        "*Generated by harvest_importer.py. A급 13 rows verbatim from 02-HARVEST_SCOPE.md. "
        "B/C 26 rows produced by 5-rule algorithm.*"
    )
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    import sys

    print("decision_builder module — use via harvest_importer.py")
    print("Functions: judge(entry, body, blacklist) -> (verdict, rationale)")
    print("           build_decisions_md(entries, blacklist, scope, conflict, out)")
    sys.exit(0)
